import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import DashboardLayout from "@/components/DashboardLayout"
import AppContext from "@/components/Provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppContext>
          <DashboardLayout>
            {children}
          </DashboardLayout>
        </AppContext>
      </body>
    </html>
  );
}
